# Deployment file for Dounebain Diagnostics
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
  DEMO_SERVER_PRIVATE_KEY: ${{ secrets.DEMO_SERVER_PRIVATE_KEY }}
  DEMO_SERVER_IP: ${{ secrets.DEMO_SERVER_IP }}
  DEMO_SERVER_USERNAME: ${{ secrets.DEMO_SERVER_USER }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Docker system prune
        run: docker system prune -af